# Netlify configuration for Storybook deployment

[build]
  command = "npm run build"
  publish = "storybook-static"

[build.environment]
  NODE_VERSION = "22"

# Prevent Netlify from auto-detecting and running the Next.js plugin
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"